In [17]:
import sys
import numpy as np

## Basics Numpy Arrays 

In [18]:
np.array([1,2,3])

array([1, 2, 3])

In [19]:
a = np.array([1,2,3,4])
b = np.array([0.5,6.2,75.1,8.2])

In [20]:
a[0] , a[1]

(np.int64(1), np.int64(2))

In [21]:
a[0:]

array([1, 2, 3, 4])

In [22]:
a[1:3]

array([2, 3])

### Arrays Types

In [23]:
a.dtype

dtype('int64')

In [24]:
b.dtype

dtype('float64')

In [ ]:
np.array(a, dtype=np.float16) # There is (float16, float32, float64)

array([1., 2., 3., 4.], dtype=float16)

In [34]:
np.array(b,dtype=np.int8)# There is (int8 , int16 , int32 , int64)

array([ 0,  6, 75,  8], dtype=int8)

### Dimensions and shapes

In [37]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [38]:
A.shape

(2, 3)

In [39]:
A.ndim

2

In [40]:
A.size

6

In [ ]:
B = np.array([
    [
        [12,13,14],
        [15,16,17]
    ],
    [
        [20,21,22],
        [23,24,25]
    ]
])

In [43]:
B.shape

(2, 2, 3)

In [44]:
B.size

12

In [45]:
B.dtype

dtype('int64')

In [46]:
B[0]

array([[12, 13, 14],
       [15, 16, 17]])

##### Square Matrix

In [ ]:

C = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [49]:
C[0][1]

np.int64(2)

In [50]:
C[0,1]

np.int64(2)

##### Replace Items

In [51]:
C[1] = np.array([10,10,10])

In [52]:
C

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [53]:
C[2] = 99

In [54]:
C

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

### Summary Statics

In [55]:
a = np.array([1,2,3,4])

In [56]:
a.sum() # => +

np.int64(10)

In [57]:
a.mean() # => sigma(x)/items(x)

np.float64(2.5)

In [58]:
a.std()

np.float64(1.118033988749895)

In [61]:
C.sum(axis=1) # => 1=row , 0=column

array([  6,  30, 297])

In [63]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [64]:
a+10

array([10, 11, 12, 13])

In [66]:
a*10

array([ 0, 10, 20, 30])

In [67]:
b=np.arange(4)
b

array([0, 1, 2, 3])

In [68]:
b + a

array([0, 2, 4, 6])

In [69]:
b*a

array([0, 1, 4, 9])